name: environmentExample
channels:
  - conda-forge
  - defaults
  - nvidia
  - fastchan
  - main
dependencies:
  - accelerate==0.26.1
  - addict==2.4.0
  - aiohttp==3.9.1
  - aiosignal==1.3.1
  - alembic==1.13.1
  - Werkzeug==3.0.1
  - wrapt==1.16.0
  - yapf==0.40.2
  - yarl==1.9.4
  - zipp==3.17.0
  - pip
  - pip:
      - tensorboard_logger==0.1.0
      - regex==2023.6.3 
      - opt-einsum==v3.3.0
      - torchvision==0.16.2
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.1.2+cu121





